CREATE DATABASE SISTEMA_MATRICULA;

USE SISTEMA_MATRICULA;

CREATE TABLE CURSO(
ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
NOME_CURSO VARCHAR(100) NOT NULL,
CARGA_HORARIA INT NOT NULL
);

CREATE TABLE TURMA (
  ID_TURMA INT PRIMARY KEY AUTO_INCREMENT,
  ANO YEAR NOT NULL,
  SEMESTRE TINYINT NOT NULL CHECK (SEMESTRE IN (1,2)),
  ID_CURSO INT NOT NULL,
  CONSTRAINT FK_TURMA_CURSO
  FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

CREATE TABLE ALUNOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
EMAIL VARCHAR(20),
CPF_NUM CHAR(11) NOT NULL,
CPF_FOR CHAR(14) GENERATED ALWAYS AS (
CONCAT(
      SUBSTRING(cpf_num, 1, 3), '.', 
      SUBSTRING(cpf_num, 4, 3), '.', 
      SUBSTRING(cpf_num, 7, 3), '-', 
      SUBSTRING(cpf_num, 10, 2)
      ) 
     ) STORED, 
     UNIQUE (CPF_FOR),
ENDERECO VARCHAR(50), 
TELEFONE CHAR(11),
CONSTRAINT UQ_ALUNOS_CPFNUM UNIQUE (CPF_NUM)
);

CREATE TABLE MATERIA (
  ID_MATERIA INT PRIMARY KEY AUTO_INCREMENT,
  NOME_MATERIA VARCHAR(100) NOT NULL,
  ID_CURSO INT NOT NULL,
  CONSTRAINT FK_MATERIA_CURSO
  FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

CREATE TABLE MATRICULA (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ID_ALUNO INT NOT NULL,
  ID_TURMA INT NOT NULL,
  STATUS BOOLEAN DEFAULT TRUE,
  DATA_MATRICULA DATE NOT NULL,
  CONSTRAINT FK_MATRICULA_ALUNO
  FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID),
  CONSTRAINT FK_MATRICULA_TURMA
  FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
)
