CREATE DATABASE SISTEMA_MATRICULA;

USE SISTEMA_MATRICULA;

CREATE TABLE CURSO(
ID_CURSO INT PRIMARY KEY AUTO_INCREMENT,
NOME_CURSO VARCHAR(100) NOT NULL,
CARGA_HORARIA INT NOT NULL
);

CREATE TABLE TURMA (
  ID_TURMA INT PRIMARY KEY AUTO_INCREMENT,
  ANO YEAR NOT NULL,
  SEMESTRE TINYINT NOT NULL CHECK (SEMESTRE IN (1,2)),
  ID_CURSO INT NOT NULL,
  CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

CREATE TABLE ALUNOS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(100),
  EMAIL VARCHAR(100),
  CPF_NUM CHAR(11) NOT NULL CHECK (CPF_NUM REGEXP '^[0-9]{11}$'),
  CPF_FOR CHAR(14) GENERATED ALWAYS AS (
    CONCAT(
      SUBSTRING(CPF_NUM, 1, 3), '.', 
      SUBSTRING(CPF_NUM, 4, 3), '.', 
      SUBSTRING(CPF_NUM, 7, 3), '-', 
      SUBSTRING(CPF_NUM, 10, 2)
    )
  ) STORED,
  ENDERECO VARCHAR(100),
  TELEFONE CHAR(11) CHECK (TELEFONE REGEXP '^[0-9]{10,11}$'),
  CONSTRAINT UQ_ALUNOS_CPFNUM UNIQUE (CPF_NUM)
);

CREATE TABLE MATERIA (
  ID_MATERIA INT PRIMARY KEY AUTO_INCREMENT,
  NOME_MATERIA VARCHAR(100) NOT NULL
);

CREATE TABLE CURSO_MATERIA (
  ID_CURSO INT NOT NULL,
  ID_MATERIA INT NOT NULL,
  PRIMARY KEY (ID_CURSO, ID_MATERIA),
  CONSTRAINT FK_CM_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
  CONSTRAINT FK_CM_MATERIA FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID_MATERIA)
);

CREATE TABLE MATRICULA (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  ID_ALUNO INT NOT NULL,
  ID_TURMA INT NOT NULL,
  STATUS BOOLEAN DEFAULT TRUE,
  DATA_MATRICULA DATE NOT NULL,
  CONSTRAINT FK_MATRICULA_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID),
  CONSTRAINT FK_MATRICULA_TURMA FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
);

CREATE INDEX IX_CM_CURSO            ON CURSO_MATERIA(ID_CURSO);
CREATE INDEX IX_CM_MATERIA          ON CURSO_MATERIA(ID_MATERIA);
CREATE INDEX IX_TURMA_ID_CURSO      ON TURMA(ID_CURSO);
CREATE INDEX IX_MATRICULA_ID_ALUNO  ON MATRICULA(ID_ALUNO);
CREATE INDEX IX_MATRICULA_ID_TURMA  ON MATRICULA(ID_TURMA);